apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: model-service-service-monitor
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: model-service
  endpoints:
  - interval: 5s