name: Build And Push
run-name: Build & Push model-service by @${{ github.actor }}
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  job_1:
    name: Build & Push
    runs-on: self-hosted
    steps:
      - name: Checkout model-service repo
        uses: actions/checkout@v3
      - name: Checkout model-training repo
        uses: actions/checkout@v3
        with:
          repository: remla23-team09/model-training
          branch: cookiecutter+dvc
          path: ./model-training
      - name: Registry Login (ghcr.io)
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u $.lowercase --password-stdin
      - name: Parse version info from tag
        run: |
          # GITHUB_REF is like refs/tags/v2.3.5, so strip the first 11 chars
          VERSION=${GITHUB_REF:11}
          MAJOR=`echo "$VERSION" | cut -d . -f 1`
          MINOR=`echo "$VERSION" | cut -d . -f 2`
          PATCH=`echo "$VERSION" | cut -d . -f 3`
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version_major=$MAJOR" >> $GITHUB_ENV
          echo "version_minor=$MINOR" >> $GITHUB_ENV
          echo "version_patch=$PATCH" >> $GITHUB_ENV
      - id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }} 
      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Fetch dvc files in model-training
        run: dvc pull
        working-directory: /home/krzysztof_garbowicz/actions-runner/_work/model-service/model-service/model-training
      - name: Recreate the models
        run: dvc repro
        working-directory: /home/krzysztof_garbowicz/actions-runner/_work/model-service/model-service/model-training
      - name: Copy data to model-service
        run: cp -r /home/krzysztof_garbowicz/actions-runner/_work/model-service/model-service/model-training/data /home/krzysztof_garbowicz/actions-runner/_work/model-service/model-service/
      - name: Copy models to model-service
        run: cp -r /home/krzysztof_garbowicz/actions-runner/_work/model-service/model-service/model-training/models /home/krzysztof_garbowicz/actions-runner/_work/model-service/model-service/
      - name: Build and Push Docker Image
        working-directory: /home/krzysztof_garbowicz/actions-runner/_work/model-service/model-service/
        run: |
          IMG=ghcr.io/${{steps.string.outputs.lowercase}}
          docker build \
            --tag $IMG:${{ env.version }} \
            --tag $IMG:${{ env.version_major }}.${{ env.version_minor }}.latest \
            --tag $IMG:${{ env.version_major }}.latest \
            --tag $IMG:latest \
            .
          docker push --all-tags $IMG