name: Build And Push
run-name: Build & Push model-service by @${{ github.actor }}
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  job_1:
    name: Build & Push
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Registry Login (ghcr.io)
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u $.lowercase --password-stdin
      - name: Parse version info from tag
        run: |
          # GITHUB_REF is like refs/tags/v2.3.5, so strip the first 11 chars
          VERSION=${GITHUB_REF:11}
          MAJOR=`echo "$VERSION" | cut -d . -f 1`
          MINOR=`echo "$VERSION" | cut -d . -f 2`
          PATCH=`echo "$VERSION" | cut -d . -f 3`
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version_major=$MAJOR" >> $GITHUB_ENV
          echo "version_minor=$MINOR" >> $GITHUB_ENV
          echo "version_patch=$PATCH" >> $GITHUB_ENV
          echo "old_version=${MAJOR}.${MINOR}.$(( ${PATCH} - 1 ))" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}
      - name: Update Model Service image version
        uses: fjogeleit/yaml-update-action@v0.13.0
        with:
          valueFile: 'model-service-chart/values.yaml'
          branch: main
          token: ${{ secrets.GH_TOKEN }}
          message: 'Update Model Service image versions in model-service-chart/values.yaml'
          changes: |
            {
              "model_service_v1.MODEL_VERSION": "${{ env.version }}",
              "model_service_v2.MODEL_VERSION": "${{ env.old_version }}"
            } 
      - uses: actions/checkout@v3
      - name: Build and Push Docker Image
        run: |
          IMG=ghcr.io/${{steps.string.outputs.lowercase}}
          docker build \
            --tag $IMG:${{ env.version }} \
            --tag $IMG:${{ env.version_major }}.${{ env.version_minor }}.latest \
            --tag $IMG:${{ env.version_major }}.latest \
            --tag $IMG:latest \
            .
          docker push --all-tags $IMG