name: Build And Push
run-name: Build & Push model-service by @${{ github.actor }}
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  job_1:
    name: Build & Push
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout model-service repo
        uses: actions/checkout@v3
      - name: Checkout model-training repo
        uses: actions/checkout@v3
        with:
          repository: remla23-team09/model-training
          branch: cookiecutter+dvc
          path: ./model-training
      - name: Download DVC
        run: pip install dvc
      - name: Registry Login (ghcr.io)
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u $.lowercase --password-stdin
      - name: Parse version info from tag
        run: |
          # GITHUB_REF is like refs/tags/v2.3.5, so strip the first 11 chars
          VERSION=${GITHUB_REF:11}
          MAJOR=`echo "$VERSION" | cut -d . -f 1`
          MINOR=`echo "$VERSION" | cut -d . -f 2`
          PATCH=`echo "$VERSION" | cut -d . -f 3`
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version_major=$MAJOR" >> $GITHUB_ENV
          echo "version_minor=$MINOR" >> $GITHUB_ENV
          echo "version_patch=$PATCH" >> $GITHUB_ENV
      - id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}
      - name: Run DVC pipeline
        working-directory: /home/runner/work/model-service/model-service/model-training
        run: |
          ls
          dvc repro
      - name: Push to DVC Repo
        working-directory: /home/runner/work/model-service/model-service/model-training
        run: |
          dvc push
          cp ./twt_roberta_sentiment_model.pkl ../model-service/twt_roberta_sentiment_model.pkl
      - name: Build and Push Docker Image
        working-directory: /home/runner/work/model-service/model-service
        run: |
          IMG=ghcr.io/${{steps.string.outputs.lowercase}}
          docker build \
            --tag $IMG:${{ env.version }} \
            --tag $IMG:${{ env.version_major }}.${{ env.version_minor }}.latest \
            --tag $IMG:${{ env.version_major }}.latest \
            --tag $IMG:latest \
            .
          docker push --all-tags $IMG